export const ENDPOINTS = {
  //customer
  registercustomer: "api/v1/customer/register",
  logincustomer: "api/v1/customer/login",
  verifycustomer: "api/v1/customer/verify_email",
  customerforgotpassword: "api/v1/customer/forgot_password",
  resetpassword: "api/v1/customer/reset_password",
  getcustomerprofile: "api/v1/customer",
  updatecustomer: "api/v1/customer/update",
  updateprofileimage: "api/v1/customer/add_profile_image",
  customerchangepassword: "api/v1/customer/change_password",
  resendcustomerverification: "api/v1/customer/resend_verification_code",
  customerlogout: "api/v1/customer/logout",
  customerlogoutsessions: "api/v1/customer/logout_all",
  customerprofileupdate: "api/v1/customer/update",
  customerpasswordchange: "api/v1/customer/change_password",
  customerimagechange: "api/v1/customer/add_profile_image",
  allcustomers: "api/v1/customers",
  cart: "api/v1/cart",
  order: "api/v1/order",
  payment: "api/v1/payment_link",
  customrequests: "api/v1/customrequest",

  //staff
  registerstaff: "api/v1/staff/register",
  loginstaff: "api/v1/staff/login",
  verifystaff: "api/v1/staff/verify_email",
  staffforgotpassword: "api/v1/staff/forgot_password",
  staffresetpassword: "api/v1/staff/reset_password",
  getstaffprofile: "api/v1/staff",
  updatestaff: "api/v1/staff/update",
  updatestaffrole: "api/v1/staff/update_role",

  updatestaffprofileimage: "api/v1/staff/add_profile_image",
  staffchangepassword: "api/v1/staff/change_password",
  resendstaffverification: "api/v1/staff/resend_verification_code",
  allstaff: "api/v1/staffs",

  stafflogout: "api/v1/staff/logout",
  stafflogoutsessions: "api/v1/staff/logout_all",
  staffprofileupdate: "api/v1/staff/update",
  staffpasswordchange: "api/v1/staff/change_password",
  staffimagechange: "api/v1/staff/add_profile_image",

  //cms endpoints
  services: "api/v1/service",
  subservices: "api/v1/service/subservice",
  pricetier: "api/v1/service/subservice/pricetier",
  allusers: "api/v1/users",
  blogs: "api/v1/blogs",
  careers: "api/v1/careers",
  review: "api/v1/rt",
  faqs: "api/v1/faqs",
  policies: "api/v1/policies",
  teammembers: "api/v1/team_members",
  aboutus: "api/v1/about_us",
  contact: "api/v1/contacts",
  adminorders: "api/v1/admin/orders",
  admincustomorders: "api/v1/admin/customrequest",
  taskerstasks: "api/v1/tasks",
  tasks: "api/v1/admin/task",
  alltasks: "api/v1/admin/tasks",
  accept_reject_tasks: "api/v1/task/accept_reject",
  progress_cancel_complete_tasks: "api/v1/task/cancel_inprogress_complete",
};
